apiVersion: apps/v1

kind: Deployment

metadata:
  name: backend-feed

  labels:
    app: backend-feed

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend-feed

  template:
    metadata:
      labels:
        app: backend-feed

    spec:
      containers:
        - name: backend-feed

          image: samehmwafy/udagram-api-feed:v1
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: udagram-environment
            - secretRef:
                name: udagram-db-credits
